[workspace]

members = [
    "halo2_ecc",
    "halo2_utilities",
    "halo2_poseidon",
    "sinsemilla",
]

[patch.crates-io]
halo2 = { git = "https://github.com/zcash/halo2.git", rev = "236a5e37a53152b49bc8c19049bc98e67968fc1c" }
